name: myenv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.0=py313h301e4d9_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alembic=1.16.5=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - arrow-cpp=19.0.0=h8011034_4
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.0=hbfa7f16_15
  - aws-c-cal=0.9.2=h5e3027f_0
  - aws-c-common=0.12.3=hb9d3cd8_0
  - aws-c-compression=0.3.1=hafb2847_5
  - aws-c-event-stream=0.5.5=h76f0014_0
  - aws-c-http=0.10.2=h015de20_2
  - aws-c-io=0.20.1=h6b9530e_1
  - aws-c-mqtt=0.13.1=h1e5e6c0_3
  - aws-c-s3=0.8.3=h5e174a9_0
  - aws-c-sdkutils=0.2.4=hafb2847_0
  - aws-checksums=0.2.7=hafb2847_1
  - aws-crt-cpp=0.32.10=ha543af7_2
  - aws-sdk-cpp=1.11.528=h9e09249_1
  - bcrypt=5.0.0=py313h843e2db_0
  - blas=1.0=mkl
  - blinker=1.9.0=pyhff2d567_0
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cachetools=6.2.0=pyhd8ed1ab_0
  - certifi=2025.11.12=py313h06a4308_0
  - cffi=1.17.1=py313hfab6e84_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py313hdb19cb5_0
  - cryptography=46.0.2=py313hafb0bba_0
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - databricks-sdk=0.67.0=pyhd8ed1ab_0
  - debugpy=1.8.14=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - dnspython=2.8.0=pyhcf101f3_0
  - docker-py=7.1.0=pyhd8ed1ab_1
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - et_xmlfile=1.1.0=py313h06a4308_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fastapi=0.118.2=h6533304_0
  - fastapi-cli=0.0.13=pyhcf101f3_0
  - fastapi-core=0.118.2=pyhcf101f3_0
  - flask=3.1.2=pyhd8ed1ab_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.7.0=py313h6b9daa2_0
  - gflags=2.2.2=h5888daf_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.5.0=h48cff8f_0
  - google-auth=2.41.1=pyhd8ed1ab_0
  - graphene=3.4.3=pyhd8ed1ab_1
  - graphql-core=3.2.6=pyh29332c3_0
  - graphql-relay=3.2.0=pyhd8ed1ab_1
  - greenlet=3.2.4=py313h7033f15_1
  - gunicorn=23.0.0=py313h78bf25f_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.6.4=py313h07c4f96_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.10=pyhd8ed1ab_1
  - imbalanced-learn=0.14.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - invoke=2.2.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.3.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.5=py313h06a4308_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - jsonschema=4.25.0=py313h06a4308_1
  - jsonschema-specifications=2025.9.1=py313h06a4308_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyterlab_widgets=3.0.15=py313h06a4308_0
  - keras=2.6.0=pyhd3eb1b0_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lazypredict=0.2.16=pyhd8ed1ab_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=15.1.0=h767d61c_2
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - liblightgbm=4.6.0=cuda_h897a41e_4
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=hba17884_3
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=hd8eb582_4
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxgboost=3.0.5=cuda129_h54c741a_1
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - lightgbm=4.6.0=cuda_py_4
  - llvmlite=0.44.0=py313hc1e8f15_1
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.3.10=pyhd8ed1ab_0
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib=3.10.0=py313h06a4308_1
  - matplotlib-base=3.10.0=py313h68cf311_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - mlflow=3.2.0=h78bf25f_1
  - mlflow-skinny=3.2.0=h78bf25f_1
  - mlflow-ui=3.2.0=py313h78bf25f_1
  - multidict=6.6.3=py313h8060acc_0
  - mysql=8.4.0=h721767e_2
  - narwhals=2.7.0=py313h06a4308_0
  - nbformat=5.10.4=py313h06a4308_0
  - nccl=2.27.7.1=h49b9d9a_3
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py313h06a4308_0
  - numba=0.61.2=py313h6a678d5_0
  - numexpr=2.10.1=py313h3c60e43_0
  - numpy=2.2.5=py313h8d96ed3_0
  - numpy-base=2.2.5=py313h8e760e0_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py313h5eee18b_1
  - openssl=3.5.4=h26f9b46_0
  - opentelemetry-api=1.37.0=pyhd8ed1ab_0
  - opentelemetry-sdk=1.37.0=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.58b0=pyh3cfb1c2_0
  - orc=2.1.1=hd396ef6_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py313h6a678d5_0
  - paramiko=4.0.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py313hac6e08b_1
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - plotly=6.3.0=py313h7040dfc_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py313h8060acc_0
  - protobuf=5.29.3=py313he621ea3_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.0.5=cuda129_pyh3031c10_1
  - pyarrow=19.0.0=py313h7934f7d_2
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.10=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py313h4b2b08d_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py313h5eee18b_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=6.7.1=py313h6a678d5_1
  - pyqt6-sip=13.9.1=py313h5eee18b_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - pytest-runner=6.0.0=pyhd8ed1ab_0
  - python=3.13.5=h4612cfd_100_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-fastjsonschema=2.21.2=py313h06a4308_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.3=py313h3dea7bd_0
  - pyzmq=26.2.0=py313h6a678d5_0
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - querystring_parser=1.2.4=pyhd8ed1ab_2
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h5eee18b_0
  - referencing=0.37.0=py313h06a4308_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.1.0=pyhe01879c_0
  - rich-toolkit=0.15.1=pyhcf101f3_0
  - rpds-py=0.28.0=py313h498d7c9_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - s2n=1.5.22=h96f233e_0
  - scikit-learn=1.7.2=py313h06d4379_0
  - scipy=1.15.3=py313h7f54423_0
  - seaborn=0.13.2=py313h06a4308_3
  - setuptools=72.1.0=py313h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sip=6.10.0=py313h6a678d5_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.43=py313h07c4f96_1
  - sqlite=3.45.3=h5eee18b_0
  - sqlparse=0.5.3=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.48.0=pyhfdc7a7d_0
  - statsmodels=0.14.5=py313ha014f3b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.14=h993c535_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.1=py313h536fd9c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.19.2=pyhef33e25_0
  - typer-slim=0.19.2=pyhcf101f3_0
  - typer-slim-standard=0.19.2=h6e3bb38_0
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvicorn=0.37.0=pyh31011fe_0
  - uvicorn-standard=0.37.0=h31011fe_0
  - uvloop=0.21.0=py313h536fd9c_1
  - watchfiles=1.1.0=py313h5c7d99a_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=15.0.1=py313h54dd161_2
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py313h06a4308_0
  - widgetsnbextension=4.0.13=py313h06a4308_0
  - wrapt=1.17.3=py313h07c4f96_1
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xgboost=3.0.5=cuda129_pyh5c66634_1
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - yarl=1.20.1=py313h8060acc_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py313h07c4f96_3
  - zstd=1.5.6=hc292b87_0
  - pip:
      - arch==7.2.0
      - blackscholes==0.2.0
      - mpmath==1.3.0
      - quantlib==1.38
      - sympy==1.14.0
prefix: /home/ge-murillo/anaconda3/envs/myenv
