name: cadenas_parcial2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - numba>=0.56.0
  - joblib>=1.0.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipython>=7.25.0
  - pip
  - pip:
    - notebook>=6.4.0
